### ISSUE TITLE
Can't connect to running xmpp server

### ISSUE THREAD

**Issue by bricekams** [vsevex/whixp#46]
I have a running xmpp server on my machine (Ejabberd)
I can read the doc at localhost:5820

But whenever I try to connect to that server I get theses errors:

```dart
  final whixp = Whixp(
    jabberID: 'admin@localhost',
    password: '1234',
    host: '192.168.1.229',

    logger: Log(enableWarning: true, enableError: true, includeTimestamp: true),
    reconnectionPolicy: RandomBackoffReconnectionPolicy(15, 30),
  );
```

```
✓ Built build/app/outputs/flutter-apk/app-debug.apk
Debug service listening on ws://127.0.0.1:44653/uSEWJWU5zpA=/ws
Syncing files to device sdk gphone x86...
I/flutter ( 1487): [Whixp] 12:03:44.964 Resetting reconnection policy
I/flutter ( 1487): [Whixp] 12:03:44.982 Trying to connect to 192.168.1.229 on port 5222
D/ProfileInstaller( 1487): Installing profile for com.example.mobile
I/flutter ( 1487): [Whixp] 12:03:47.494 Error occured while trying to connect to 192.168.1.229
I/flutter ( 1487): [Whixp] 12:03:47.509 Connection is lost
I/flutter ( 1487): [Whixp] 12:03:47.512 Session ended
I/flutter ( 1487): [Whixp] 12:03:47.514 Disconnect method is called
E/flutter ( 1487): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PathNotFoundException: Creation failed, path = '' (OS Error: No such file or directory, errno = 2)
E/flutter ( 1487): #0      _checkForErrorResponse (dart:io/common.dart:55:9)
E/flutter ( 1487): #1      _Directory.create.<anonymous closure> (dart:io/directory_impl.dart:109:9)
E/flutter ( 1487): <asynchronous suspension>
E/flutter ( 1487): #2      BackendManager.open (package:hive/src/backend/vm/backend_manager.dart:34:7)
E/flutter ( 1487): <asynchronous suspension>
E/flutter ( 1487): #3      HiveImpl._openBox (package:hive/src/hive_impl.dart:101:21)
E/flutter ( 1487): <asynchronous suspension>
E/flutter ( 1487): #4      HiveImpl.openBox (package:hive/src/hive_impl.dart:142:12)
E/flutter ( 1487): <asynchronous suspension>
E/flutter ( 1487): #5      HiveController.initialize (package:whixp/src/database/controller.dart:29:14)
E/flutter ( 1487): <asynchronous suspension>
E/flutter ( 1487): #6      new Transport._internal.<anonymous closure> (package:whixp/src/transport.dart:177:9)
E/flutter ( 1487): <asynchronous suspension>
E/flutter ( 1487): #7      Connection._onStart (package:whixp/src/connection.dart:132:5)
E/flutter ( 1487): <asynchronous suspension>
E/flutter ( 1487): #8      Connection.start (package:whixp/src/connection.dart:112:7)
E/flutter ( 1487): <asynchronous suspension>
E/flutter ( 1487): 
I/flutter ( 1487): [Whixp] 12:03:47.528 Failure occured. Starting random backoff with 16s
E/flutter ( 1487): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field '_waitingQueueController@177438461' has not been initialized.
E/flutter ( 1487): #0      Transport._waitingQueueController (package:whixp/src/transport.dart)
E/flutter ( 1487): #1      Transport._closeStreams (package:whixp/src/transport.dart:667:5)
E/flutter ( 1487): #2      Transport._setup.<anonymous closure> (package:whixp/src/transport.dart:281:9)
E/flutter ( 1487): #3      Eventius.emit (package:whixp/src/handler/eventius.dart:135:17)
E/flutter ( 1487): #4      Transport.emit (package:whixp/src/transport.dart:462:17)
E/flutter ( 1487): #5      new Transport._internal.<anonymous closure> (package:whixp/src/transport.dart:174:18)
E/flutter ( 1487): #6      Connection.hangup.consumeSend (package:whixp/src/connection.dart:159:29)
E/flutter ( 1487): #7      Connection.hangup (package:whixp/src/connection.dart:164:14)
E/flutter ( 1487): #8      Transport._connectionLost (package:whixp/src/transport.dart:396:22)
E/flutter ( 1487): #9      _TCPConnecta._handleSocket.<anonymous closure> (package:connecta/src/_tcp.dart:116:19)
E/flutter ( 1487): #10     _RootZone.runGuarded (dart:async/zone.dart:1582:10)
E/flutter ( 1487): #11     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:418:13)
E/flutter ( 1487): #12     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:428:7)
E/flutter ( 1487): #13     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:317:7)
E/flutter ( 1487): #14     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:792:19)
E/flutter ( 1487): #15     _StreamController._closeUnchecked (dart:async/stream_controller.dart:647:7)
E/flutter ( 1487): #16     _StreamController.close (dart:async/stream_controller.dart:640:5)
E/flutter ( 1487): #17     _Socket.destroy (dart:io-patch/socket_patch.dart:2355:17)
E/flutter ( 1487): #18     ConnectaSocket._destroy (package:connecta/src/socket.dart:68:18)
E/flutter ( 1487): #19     Connecta.destroy (package:connecta/src/connecta.dart:171:29)
E/flutter ( 1487): #20     Connection.abort (package:whixp/src/connection.dart:371:20)
E/flutter ( 1487): #21     Connection.start (package:whixp/src/connection.dart:118:7)
E/flutter ( 1487): <asynchronous suspension>
E/flutter ( 1487): 
E/flutter ( 1487): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field '_waitingQueueController@177438461' has not been initialized.
E/flutter ( 1487): #0      Transport._waitingQueueController (package:whixp/src/transport.dart)
E/flutter ( 1487): #1      Transport._closeStreams (package:whixp/src/transport.dart:667:5)
E/flutter ( 1487): #2      Transport._connectionLost (package:whixp/src/transport.dart:399:5)
E/flutter ( 1487): <asynchronous suspension>
E/flutter ( 1487): 

```

**Comment by bricekams** [comment]
Thank you very much for your answer

**Comment by nihaocgl** [comment]
> Thank you very much for your answer
> 非常感谢您的回答
> […](#)  [...](#)

this documentation doesn't work, can you tell me how to fix this issuse

**Comment by vsevex** [comment]
@nihaocgl hi. Documentation is live again. Have a lovely coding.

**Comment by nihaocgl** [comment]
> [@nihaocgl](https://github.com/nihaocgl) hi. Documentation is live again. Have a lovely coding.

Thank you very much for your answer
but I still can't connect to the XMPP server, as shown in the screenshot.
What steps should I take to troubleshoot this?
 

![Image](https://github.com/user-attachments/assets/0f024b78-e5f5-48dd-a222-c7082e0decea)

**Comment by vsevex** [comment]
@nihaocgl, can you please log the exception to the console and share the output with me according to [this](https://whixp.dosy.app/docs/advanced/handlers#connectionfailure) documentation section?

**Comment by nihaocgl** [comment]
@vsevex , Thank you for your answer.
sure,My input parameter:
```
final whixp = Whixp(
    jabberID: 'f123***@***.com',
    password: 'f123***',
    host: '10.***.56',
    port:5222,
    disableStartTLS: true,
    useTLS: false,
    logger: Log(enableWarning: true, enableError: true, includeTimestamp: true),
    reconnectionPolicy: RandomBackoffReconnectionPolicy(1, 3),
    onBadCertificateCallback: (X509Certificate cert) {
      return true; 
    },
  );

whixp.addEventHandler<TransportState>('state', (state) {
    if (state == TransportState.connecting) {
      log('Connecting');
    } else if (state == TransportState.connected) {
      log('Connected');
    } else if (state == TransportState.disconnected) {
      log('Disconnected');
    } else if (state == TransportState.connectionFailure) {
      log('Connection failure occured');
    } else if (state == TransportState.reconnecting) {
      log('Reconnecting');
    }
  });
  whixp.addEventHandler<StreamError>('streamError', (error) {
    // Do something with the error.
    log('streamError :  ${error?.text}');
  });
  whixp.addEventHandler<String>('failedAuthentication', (reason) {
    log('Failed to authenticate: ${reason.toString()}');
  });
  whixp.addEventHandler('connectionFailure', (dynamic exception) {
    log('Connection failed: $exception');
  });
  whixp.addEventHandler('error', (dynamic error) {
    log('XMPP错误: $error');
  });
  whixp.addEventHandler('socketError', (dynamic error) {
    log('Socket错误: $error');
  });

```

**The output content is**
```
flutter: [Whixp] --15:23:12.706-- Timer elapsed. Waiting for lock...
flutter: [Whixp] --15:23:12.708-- Reconnecting...
flutter: [Whixp] --15:23:12.709-- Resetting reconnection policy
flutter: [Whixp] --15:23:12.710-- Trying to connect to 10.***.56 on port 5222
[log] Reconnecting
flutter: [Whixp] --15:23:12.715-- Error occured while trying to connect to 10.***.56
flutter: [Whixp] --15:23:12.717-- Socket is not initialized yet, aborting...
flutter: [Whixp] --15:23:12.718-- Failure occured. Starting random backoff with 2s
[log] Connecting
[log] Connection failure occured
[log] Connection failed: Connecta exception is thrown while establishing a TCP connection: SocketException: Connection failed (OS Error: No route to host, errno = 65), address = 10.***.56, port = 5222
```

How can I solve this problem of connection failure? Thank you again!

**Comment by vsevex** [comment]
`Connection failed: Connecta exception is thrown while establishing a TCP connection: SocketException: Connection failed (OS Error: No route to host, errno = 65), address = 10.***.56, port = 5222`

As you can see, your request returns a `no route to host` error. Could you double-check your server deployment? I think you forgot to enable TCP connection (SSL free) to the server.

**Comment by nihaocgl** [comment]
@vsevex The server is running normally, SSL is not enabled, and it can be connected in the iOS application.

**Comment by vsevex** [comment]
Which platform are you trying to connect to the server from now?

**Comment by nihaocgl** [comment]
Use Whixp in Flutter.

**Comment by vsevex** [comment]
I mean, it could be a firewall error, too. For that specific platform, you should check if the incoming or outgoing requests are blocked.

**Comment by nihaocgl** [comment]
When using Whixp in Flutter and running it on iOS or macOS, the connection fails. However, when using the OC XMPPFramework on an iOS mobile phone, the connection can be established normally. So I'm really confused and I don't know where the problem lies.

**Comment by vsevex** [comment]
[Maybe this solution fixes your problem?](https://stackoverflow.com/questions/79314225/flutter-run-error-socketexception-no-route-to-host-errno-65-on-ios-device)

**Comment by nihaocgl** [comment]
@vsevex  Thank you for your answer !
At present, I still can't connect to the XMPP server. It doesn't seem to be a firewall problem. It might be a TLS encryption issue. 
For example:

```
1.disableStartTLS: false,
useTLS:false
-
An error occured while Securing Socket: HandshakeException: Handshake error in client (OS Error: 
	WRONG_VERSION_NUMBER(tls_record.cc:224))
```

```
2.disableStartTLS: false,
useTLS:true
OR
disableStartTLS: true,
useTLS:true
-
 Could not pick any SRV record
 Resetting reconnection policy
 Trying to connect to 10.***.124 on port 5222
 Error occured while trying to connect to 10.***.124
 Socket is not initialized yet, aborting...
 Failure occured. Starting random backoff with 2s
 Timer elapsed. Waiting for lock...
 Reconnecting...
```

```
3.disableStartTLS: true,
useTLS:flase
-
Disable StartTLS is enabled, can not negotiate handshake

```
So how can I connect to the XMPP service without using TLS encryption? Maybe after not using TLS encryption, it will be possible to connect to the XMPP service.
